services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - '80:80'
        depends_on:
            - server
        networks:
            - mern
    client:
        build: ./mern/client
        networks:
            - mern
        volumes:
            - ./mern/client/dist:/app/dist # This ensures the build output is available to nginx

    server:
        build: ./mern/server
        ports:
            - '5000:5000' # Expose the backend port
        networks:
            - mern
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        networks:
            - mern
        volumes:
            - mongo-data:/data/db

networks:
    mern:
        driver: bridge

volumes:
    mongo-data:
        driver: local # Persist MongoDB data locally
