version: '3.8'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - '80:80'
        depends_on:
            - server
        networks:
            - mern
    client:
        build: ./mern/client
        networks:
            - mern

    server:
        build: ./mern/server
        networks:
            - mern
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        networks:
            - mern
        volumes:
            - mongo-data:/data/db

networks:
    mern:
        driver: bridge

volumes:
    mongo-data:
        driver: local # Persist MongoDB data locally
